/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

#ifndef __FLS_STATS_H
#define __FLS_STATS_H

#include <linux/debugfs.h>
#include <linux/seq_file.h>
#include <linux/atomic.h>

/*
 * Debugfs root directory for FLS
 */
extern struct dentry *fls_debug_root_dir;

enum fls_conn_counters {
	FLS_CONN_RFS_ENQUEUE_XXL = 0,
	FLS_CONN_RFS_ENQUEUE_XL,
	FLS_CONN_RFS_EVENT_TYPE_DEF,
	FLS_CONN_PER_CONN_DELAY_FINISHED,
	FLS_CONN_TIMER_DELETE,
	FLS_CONN_COUNTERS_MAX
};

enum fls_conn_exception_counters {
	FLS_CONN_EXCEPTION_RFS_ENQUEUE_XXL_FAIL = 0,
	FLS_CONN_EXCEPTION_RFS_ENQUEUE_XL_FAIL,
	FLS_CONN_EXCEPTION_RFS_ENQUEUE_DEF_FAIL,
	FLS_CONN_SENSOR_HWM_EXCEEDED,
	FLS_CONN_SENSOR_MAX_EVENT_EXCEEDED,
	FLS_CONN_EXCEPTION_CANNOT_CREATE_EVENT_UNIDIR_FLOW,
	FLS_CONN_EXCEPTION_INVALID_FLAGS_WINDOW_TIMER_CALLBACK,
	FLS_CONN_EXCEPTION_DEFAULT_SENSOR_DISABLED,
	FLS_CONN_EXCEPTION_COUNTERS_MAX
};

enum fls_gbl_counters {
	FLS_GBL_ACTIVE_COUNT = 0,
	FLS_GBL_CREATE_REQUESTS,
	FLS_GBL_DELETE_REQUESTS,
	FLS_GBL_COUNTERS_MAX
};

enum fls_gbl_exception_counters {
	FLS_GBL_EXCEPTION_MEM_ALLOC_FAIL = 0,
	FLS_GBL_EXCEPTION_MAX_CONN_LIMIT,
	FLS_GBL_EXCEPTION_CHANNEL_NOT_INIT,
	FLS_GBL_RFS_BUFF_FULL,
	FLS_GBL_RFS_EXCEPTION_NO_EVENT_PENDING,
	FLS_GBL_RFS_EXCEPTION_EVENT_QUEUE_FULL,
	FLS_GBL_EXCEPTION_COUNTERS_MAX
};

void fls_stats_init(void);
void fls_stats_deinit(void);

#endif /* __FLS_STATS_H */
